name: Validate Nuget Version Number
on:
  workflow_dispatch:
  # Add the appropriate trigger for your project here (https://westshorehome.atlassian.net/l/cp/f0xFPpPb)
  # pull_request:
  #   branches:
  #     - main
  #   paths-ignore:
  #     - '**.md' # Skip if only markdown files have changed
  #     - '.github/**' # Skip if only files within the .github directory have changed
  #     - 'Documentation/**' # Skip if only files within the Documentation directory have changed
  #     - 'Code_Coverage/**' # Skip if only files within the Code_Coverage directory have changed
    
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
      
jobs:
  validate-nuget-package-version-number:
    uses: westshorehome/automation-workflows/.github/workflows/validate-nuget-package-version-number.yml@v1.4
    with:
      package_path: '[PATH_TO_PACKAGE_CSPROJ_FILE]'
      package_id: '[PACKAGE_ID]'
    secrets: inherit
